# Generated by Django 4.2.20 on 2025-04-18 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeopardy', '0002_alter_answerquestionasked_player_correct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerquestion',
            name='answer_media',
            field=models.FileField(blank=True, upload_to='answer/'),
        ),
        migrations.AddField(
            model_name='answerquestion',
            name='answer_media_type',
            field=models.CharField(choices=[('N', 'None'), ('I', 'Image'), ('A', 'Audio'), ('V', 'Video')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='answerquestion',
            name='question_media',
            field=models.FileField(blank=True, upload_to='question/'),
        ),
        migrations.AddField(
            model_name='answerquestion',
            name='question_media_type',
            field=models.CharField(choices=[('N', 'None'), ('I', 'Image'), ('A', 'Audio'), ('V', 'Video')], default='N', max_length=1),
        ),
    ]
