# Generated by Django 4.2.20 on 2025-04-18 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeopardy', '0004_alter_answerquestion_answer_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerquestion',
            name='answer_text',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='answerquestion',
            name='question_text',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
