# Generated by Django 4.2.20 on 2025-04-19 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeopardy', '0005_alter_answerquestion_answer_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerquestion',
            name='internal_notes',
            field=models.TextField(blank=True),
        ),
    ]
