# Generated by Django 4.2.20 on 2025-04-19 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jeopardy', '0006_answerquestion_internal_notes'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='answerquestionasked',
            unique_together={('answer_question', 'gameround')},
        ),
    ]
