# Generated by Django 5.2.3 on 2025-06-15 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeopardy', '0007_alter_answerquestionasked_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerquestion',
            name='attribution',
            field=models.TextField(blank=True),
        ),
    ]
