# Generated by Django 5.2.3 on 2025-06-17 19:57

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeopardy', '0008_answerquestion_attribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerquestionasked',
            name='double_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='double_player', to='jeopardy.player'),
        ),
        migrations.AddField(
            model_name='answerquestionasked',
            name='double_points',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gameround',
            name='double_frequency',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
