# Changes here will be overwritten by Copier.
_commit: 0.0.78
_src_path: https://codeberg.org/margau/copier-python-uv.git
container: false
forgejo_url: https://codeberg.org/margau/djangopardy
ignore_pylint: true
ignore_ruff: true
ignore_ruff_format: true
project_description: A django-based jeopardy tool
project_name: djangopardy
pypi_publish: false
pypi_publish_dev: false
scripts: null
