[project]
name = "djangopardy"
description = "A django-based jeopardy tool"
authors = [{name = "Vanessa Gaube", email = "dev@vanessagaube.de"}]
license = "GPL-3.0"
readme = "README.md"
requires-python = ">=3.10"
dynamic = ["version"]
dependencies = [
    "django>=5.2.3",
    "django-bootstrap5>=25.1",
]

[build-system]
requires = ["hatchling", "uv-dynamic-versioning"]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "uv-dynamic-versioning"

# TODO: URLs

# Dev Dependencies
[tool.uv]
dev-dependencies = [
  "ruff",
  "pylint",
]

# TODO: Dev/CI scripts for lint & co.