name: Build and Push Container Image

on:
  push:

env:
  REGISTRY: codeberg.org

jobs:
  build-and-push-image:
    runs-on: docker-builder
    container: 
      image: codeberg.org/margau/buildenv-container-builder:latest@sha256:7199e99a0f74a531f966f9c1379a129b20f1a8b4e708073fce45c35c038586aa
    steps:
    - uses: https://code.forgejo.org/actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      with:
        fetch-depth: 0
    - name: cache restore
      uses: https://code.forgejo.org/actions/cache/restore@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5
      with:
        path: |
          /var/lib/containers
        key: buildah-images

    - name: Docker Metadata
      id: docker-metadata
      uses: https://github.com/docker/metadata-action@c299e40c65443455700f0fdfc63efafe5b349051 # v5
      with:
        images: |
          ${{ env.REGISTRY }}/${{ github.repository }}
        tags: |
          type=sha,enable=${{ !(github.ref == format('refs/heads/{0}', 'main') || startsWith(github.ref, 'refs/tags/')) }}
          type=pep440,pattern={{version}}
          type=raw,value=main,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}

    - name: Build
      id: build-image
      uses: https://github.com/redhat-actions/buildah-build@main
      with:
        containerfiles: |
          ./Containerfile
        tags: ${{ steps.docker-metadata.outputs.tags }}
        labels: ${{ steps.docker-metadata.outputs.labels }}
        platforms: linux/amd64,linux/arm64
        layers: true
    
    - name: Push
      if: github.ref == format('refs/heads/{0}', 'main') || startsWith(github.ref, 'refs/tags/') # only push on main branch or tags
      uses: https://github.com/redhat-actions/push-to-registry@main
      with:
        image: ${{ steps.build-image.outputs.image }}
        tags: ${{ steps.build-image.outputs.tags }}
        username: ${{ github.actor }}
        password: ${{ secrets.CONTAINER_TOKEN }}

    - name: cache save
      uses: https://code.forgejo.org/actions/cache/save@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5
      with:
        path: |
          /var/lib/containers
        key: buildah-images