name: Build and Push Container Image

on:
  push:

env:
  REGISTRY: codeberg.org

jobs:
  build-and-push-image:
    runs-on: docker-builder
    container: 
      image: codeberg.org/margau/buildenv-container-builder:latest@sha256:20bd8b7132c7afc663a905caf5e5fd53fb0bf4705145cfbb5117da5b0916499d
    steps:
    - uses: https://code.forgejo.org/actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      with:
        fetch-depth: 0
    - name: cache restore
      uses: https://code.forgejo.org/actions/cache/restore@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6
      with:
        path: |
          /var/lib/containers
        key: buildah-images

    - name: Docker Metadata
      id: docker-metadata
      uses: https://github.com/docker/metadata-action@dc802804100637a589fabce1cb79ff13a1411302 # v6
      with:
        images: |
          ${{ env.REGISTRY }}/${{ github.repository }}
        tags: |
          type=sha,enable=${{ !(github.ref == format('refs/heads/{0}', 'main') || startsWith(github.ref, 'refs/tags/')) }}
          type=pep440,pattern={{version}}
          type=raw,value=main,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}

    - name: Build
      id: build-image
      uses: https://github.com/redhat-actions/buildah-build@adf46c486ef4a3c9e7047319c8f3acf989266c42 # main
      with:
        containerfiles: |
          ./Containerfile
        tags: ${{ steps.docker-metadata.outputs.tags }}
        labels: ${{ steps.docker-metadata.outputs.labels }}
        platforms: linux/amd64,linux/arm64
        layers: true
    
    - name: Push
      if: github.ref == format('refs/heads/{0}', 'main') || startsWith(github.ref, 'refs/tags/') # only push on main branch or tags
      uses: https://github.com/redhat-actions/push-to-registry@e459a35fac8e05b48ddca852748c7eeca8648c6b # main
      with:
        image: ${{ steps.build-image.outputs.image }}
        tags: ${{ steps.build-image.outputs.tags }}
        username: ${{ github.actor }}
        password: ${{ secrets.CONTAINER_TOKEN }}

    - name: cache save
      uses: https://code.forgejo.org/actions/cache/save@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6
      with:
        path: |
          /var/lib/containers
        key: buildah-images