name: Build and Push Container Image

on:
  push:

env:
  REGISTRY: codeberg.org

jobs:
  build-and-push-image:
    runs-on: docker-builder
    container: 
      image: codeberg.org/margau/buildenv-container-builder:latest@sha256:b244ded581b8b1e70f3f9470ceb6a9dac3bb3b5b93abc25dfdfde88b29d1273e
    steps:
    - uses: https://code.forgejo.org/actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      with:
        fetch-depth: 0
    - name: cache restore
      uses: https://code.forgejo.org/actions/cache/restore@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5
      with:
        path: |
          /var/lib/containers
        key: buildah-images

    - name: Docker Metadata
      id: docker-metadata
      uses: https://github.com/docker/metadata-action@030e881283bb7a6894de51c315a6bfe6a94e05cf # v6
      with:
        images: |
          ${{ env.REGISTRY }}/${{ github.repository }}
        tags: |
          type=sha,enable=${{ !(github.ref == format('refs/heads/{0}', 'main') || startsWith(github.ref, 'refs/tags/')) }}
          type=pep440,pattern={{version}}
          type=raw,value=main,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}

    - name: Build
      id: build-image
      uses: https://github.com/redhat-actions/buildah-build@061ffd31bb5c3f8733a6f9bbdf00a9fb02eb708c # main
      with:
        containerfiles: |
          ./Containerfile
        tags: ${{ steps.docker-metadata.outputs.tags }}
        labels: ${{ steps.docker-metadata.outputs.labels }}
        platforms: linux/amd64,linux/arm64
        layers: true
    
    - name: Push
      if: github.ref == format('refs/heads/{0}', 'main') || startsWith(github.ref, 'refs/tags/') # only push on main branch or tags
      uses: https://github.com/redhat-actions/push-to-registry@3916dcf329473955be3059ef62c9c062ea1b9054 # main
      with:
        image: ${{ steps.build-image.outputs.image }}
        tags: ${{ steps.build-image.outputs.tags }}
        username: ${{ github.actor }}
        password: ${{ secrets.CONTAINER_TOKEN }}

    - name: cache save
      uses: https://code.forgejo.org/actions/cache/save@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5
      with:
        path: |
          /var/lib/containers
        key: buildah-images