name: pytest

on:
  push:
    branches:
      - main
  # non-main branches are handled by pull_request
  pull_request:

jobs:
  pytest:
    runs-on: docker
    container:
      image: codeberg.org/margau/buildenv-uv:latest@sha256:4625e27c770668e96a4efbb72980b45d4f7ec2ae879d03c5e0af2c977bb6b75b

    steps:
      - uses: https://code.forgejo.org/actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0
      - name: Install the project
        run: uv sync --locked --all-extras --dev
      - name: run pytest
        run: uv run coverage run -m pytest -v || exit 0 
      - name: show coverage
        run: uv run coverage report -m
